# -*- coding: utf-8 -*-
"""IDL_Ex1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vybBJr-EXgYkiPMwNQz5TEcOtIM3aH0U
"""
====================
#   Questions 2.a  #
====================

# uploading the data
from google.colab import files
uploaded = files.upload()

import zipfile
with zipfile.ZipFile("ex1_data.zip", 'r') as zip_ref:
    zip_ref.extractall("data")

# sanity check - should see allele names and neg class
import os
os.listdir("data")

# creating the data set
import os
import pandas as pd

data = []
# folder = "data/Ex1 data"
folder = "data"

for filename in os.listdir(folder):
    if not filename.endswith(".txt"):
        continue
    filepath = os.path.join(folder, filename)
    # determine label
    if filename == "negs.txt":
        label = "NEG"
    else:
        label = filename.replace("_pos.txt", "")
    with open(filepath, "r") as f:
        for line in f:
            peptide = line.strip()
            if len(peptide) == 9:
                data.append([peptide, label])

df = pd.DataFrame(data, columns=["peptide", "label"])
print(df.head())
print(df["label"].value_counts())

# mapping allele names to class labels - integers
import numpy as np
# get unique and repeatable labels
labels = sorted(df["label"].unique())
print(labels)
label_to_idx = {label: i for i, label in enumerate(labels)}
idx_to_label = {i: label for label, i in label_to_idx.items()}
print(label_to_idx)
df["label_idx"] = df["label"].map(label_to_idx)
df.head()

# checking how many unique peptides are
num_unique = df["peptide"].nunique()
print(num_unique)

# checking what letters compose the acids
unique_chars = set()

for peptide in df["peptide"]:
    for aa in peptide:
        unique_chars.add(aa)

print(sorted(unique_chars))
print(len(unique_chars))

# vectorizing the data
X = df["peptide"].values
y = df["label_idx"].values

# create mapping from amino acid to index
aa_to_idx = {aa: i for i, aa in enumerate(unique_chars)}
# encode peptide function
import numpy as np
def encode_peptide(peptide):
    mat = np.zeros((9, len(unique_chars)))  # (9, 20)
    for i, aa in enumerate(peptide):
        mat[i, aa_to_idx[aa]] = 1
    return mat.flatten()  # (180,)

X_encoded = np.array([encode_peptide(p) for p in X])
print("Encoded shape:", X_encoded.shape)
# sainty check
# check values are only 0/1
print("Unique values in X_encoded:", np.unique(X_encoded))
# check each row has exactly 9 ones (one per position)
print("Ones per sample (first 5):", X_encoded.sum(axis=1)[:5])

====================
#   Questions 1    #
====================

# splitting train and test
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_encoded,
    y,
    test_size=0.1,
    random_state=42,
    stratify=y  # to keep all classes in both sets
)
# check sets size and class distributions
print("Train size:", X_train.shape)
print("Test size:", X_test.shape)
import numpy as np
print("Train distribution:", np.bincount(y_train))
print("Test distribution:", np.bincount(y_test))

# implementing the MLP
import torch
import torch.nn as nn
import torch.optim as optim

# converting all the df to tensors
X_train_t = torch.tensor(X_train, dtype=torch.float32)
y_train_t = torch.tensor(y_train, dtype=torch.long)
X_test_t = torch.tensor(X_test, dtype=torch.float32)
y_test_t = torch.tensor(y_test, dtype=torch.long)

====================
#   Questions 2.b  #
====================

class MLP(nn.Module):
    def __init__(self):
        super().__init__()

        self.net = nn.Sequential(
            nn.Linear(180, 180),
            nn.ReLU(),
            nn.Linear(180, 180),
            nn.ReLU(),
            nn.Linear(180, 7)
        )

    def forward(self, x):
        return self.net(x)

model = MLP()

# choosing loss and optimizer
import torch
import torch.nn as nn
import torch.optim as optim
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=1e-3)

# define accuracy metric
def compute_accuracy(outputs, labels):
    preds = torch.argmax(outputs, dim=1)
    correct = (preds == labels).sum().item()
    total = labels.size(0)
    return correct / total

# use colab's GPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)
model = MLP().to(device)
X_train_t = X_train_t.to(device)
y_train_t = y_train_t.to(device)
X_test_t = X_test_t.to(device)
y_test_t = y_test_t.to(device)

train_losses = []
test_losses = []

train_accuracies = []
test_accuracies = []

epochs = 20

for epoch in range(epochs):

    # ---- TRAIN ----
    model.train()
    optimizer.zero_grad()

    outputs = model(X_train_t)
    loss = criterion(outputs, y_train_t)

    loss.backward()
    optimizer.step()

    train_losses.append(loss.item())

    train_acc = compute_accuracy(outputs, y_train_t)
    train_accuracies.append(train_acc)

    # ---- TEST ----
    model.eval()
    with torch.no_grad():
        test_outputs = model(X_test_t)
        test_loss = criterion(test_outputs, y_test_t)
        test_losses.append(test_loss.item())

        test_acc = compute_accuracy(test_outputs, y_test_t)
        test_accuracies.append(test_acc)

    print(f"Epoch {epoch+1}: "
          f"Train Loss = {loss.item():.4f}, "
          f"Test Loss = {test_loss.item():.4f}, "
          f"Train Acc = {train_acc:.4f}, "
          f"Test Acc = {test_acc:.4f}")

import matplotlib.pyplot as plt

plt.plot(train_losses, label="Train Loss")
plt.plot(test_losses, label="Test Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.title("Training vs Test Loss")
plt.show()

plt.plot(train_accuracies, label="Train Accuracy")
plt.plot(test_accuracies, label="Test Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend()
plt.title("Training vs Test Accuracy")
plt.show()

with torch.no_grad():
    outputs = model(X_train_t[:5])
    print(outputs)

import numpy as np
import matplotlib.pyplot as plt

all_grads = []

for name, param in model.named_parameters():
    if param.grad is not None:
        grads = param.grad.detach().cpu().numpy().flatten()
        all_grads.append(grads)

all_grads = np.concatenate(all_grads)
print("Gradient stats:")
print(f"Mean: {all_grads.mean():.6f}")
print(f"Std:  {all_grads.std():.6f}")
print(f"Min:  {all_grads.min():.6f}")
print(f"Max:  {all_grads.max():.6f}")

plt.hist(all_grads, bins=100)
plt.title("Gradient Distribution")
plt.show()

====================
#   Questions 2.c  #
====================

# using Dataset and DataLoader for batch training
import torch
from torch.utils.data import TensorDataset, DataLoader

train_dataset = TensorDataset(X_train_t, y_train_t)
test_dataset = TensorDataset(X_test_t, y_test_t)

batch_size = 128

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

# implementing the improved MLP
import torch.nn as nn
class BetterMLP(nn.Module):
    def __init__(self):
        super().__init__()

        self.net = nn.Sequential(
            nn.Linear(180, 32),
            nn.ReLU(),

            nn.Linear(32, 16),
            nn.ReLU(),

            nn.Linear(16, 7)
        )

    def forward(self, x):
        return self.net(x)

# CE loss with class weights
import numpy as np
import torch

class_counts = np.bincount(y_train)
class_weights = 1.0 / class_counts
class_weights = class_weights / class_weights.sum() * len(class_weights)
class_weights = torch.tensor(class_weights, dtype=torch.float32).to(device)

print("Class counts:", class_counts)
print("Class weights:", class_weights)

criterion = nn.CrossEntropyLoss(weight=class_weights)

model_better = BetterMLP().to(device)

optimizer = torch.optim.Adam(model_better.parameters(), lr=1e-3)

train_losses = []
test_losses = []

epochs = 30

for epoch in range(epochs):
    best_loss = float('inf')
    # ---- TRAIN ----
    model_better.train()
    running_train_loss = 0.0

    for xb, yb in train_loader:
        xb = xb.to(device)
        yb = yb.to(device)

        optimizer.zero_grad()
        outputs = model_better(xb)
        loss = criterion(outputs, yb)
        loss.backward()
        optimizer.step()

        running_train_loss += loss.item() * xb.size(0)

    epoch_train_loss = running_train_loss / len(train_loader.dataset)
    train_losses.append(epoch_train_loss)

    # ---- TEST ----
    model_better.eval()
    running_test_loss = 0.0

    with torch.no_grad():
        for xb, yb in test_loader:
            xb = xb.to(device)
            yb = yb.to(device)

            outputs = model_better(xb)
            loss = criterion(outputs, yb)
            running_test_loss += loss.item() * xb.size(0)

    epoch_test_loss = running_test_loss / len(test_loader.dataset)
    test_losses.append(epoch_test_loss)
    if epoch_test_loss < best_loss:
      best_loss = epoch_test_loss
      torch.save(model_better.state_dict(), "best_model.pth")

    print(f"Epoch {epoch+1}: Train Loss = {epoch_train_loss:.4f}, Test Loss = {epoch_test_loss:.4f}")

import matplotlib.pyplot as plt

plt.plot(train_losses, label="Train Loss")
plt.plot(test_losses, label="Test Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Better MLP: Train vs Test Loss")
plt.legend()
plt.show()

# loading the model of the best epoch
model_best = BetterMLP().to(device)
model_best.load_state_dict(torch.load("best_model.pth", map_location=device))
model_best.eval()

import numpy as np

def per_class_accuracy(outputs, labels, num_classes=7):
    preds = torch.argmax(outputs, dim=1)

    preds = preds.cpu().numpy()
    labels = labels.cpu().numpy()

    accs = []

    for c in range(num_classes):
        mask = labels == c

        if np.sum(mask) == 0:
            accs.append(0)
        else:
            acc = np.mean(preds[mask] == labels[mask])
            accs.append(acc)

    return accs

with torch.no_grad():
    outputs = model_best(X_test_t)
    accs = per_class_accuracy(outputs, y_test_t)

for i, acc in enumerate(accs):
    print(f"Class {i} accuracy: {acc:.3f}")

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

with torch.no_grad():
    preds = torch.argmax(model_best(X_test_t), dim=1)

cm = confusion_matrix(y_test_t.cpu(), preds.cpu())

plt.figure(figsize=(8,6))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues")
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Confusion Matrix")
plt.show()

import numpy as np
import matplotlib.pyplot as plt

model_best.train()  # enable gradients

optimizer.zero_grad()

outputs = model_best(X_train_t)
loss = criterion(outputs, y_train_t)

loss.backward()

all_grads = []

for name, param in model_best.named_parameters():
    if param.grad is not None:
        grads = param.grad.detach().cpu().numpy().flatten()
        all_grads.append(grads)

all_grads = np.concatenate(all_grads)
print("Gradient stats:")
print(f"Mean: {all_grads.mean():.6f}")
print(f"Std:  {all_grads.std():.6f}")
print(f"Min:  {all_grads.min():.6f}")
print(f"Max:  {all_grads.max():.6f}")

plt.hist(all_grads, bins=100)
plt.title("Gradient Distribution")
plt.show()

====================
#   Questions 2.d  #
====================

# removing non-linear operators
import torch.nn as nn

class LinearMLP(nn.Module):
    def __init__(self):
        super().__init__()

        self.net = nn.Sequential(
            nn.Linear(180, 32),
            nn.Linear(32, 16),
            nn.Linear(16, 7)
        )

    def forward(self, x):
        return self.net(x)

model_linear = LinearMLP().to(device)

criterion = nn.CrossEntropyLoss(weight=class_weights)  # same as before
optimizer = torch.optim.Adam(model_linear.parameters(), lr=1e-3)

train_losses = []
test_losses = []

epochs = 30

for epoch in range(epochs):

    # ---- TRAIN ----
    model_linear.train()
    running_train_loss = 0.0

    for xb, yb in train_loader:
        xb = xb.to(device)
        yb = yb.to(device)

        optimizer.zero_grad()
        outputs = model_linear(xb)
        loss = criterion(outputs, yb)
        loss.backward()
        optimizer.step()

        running_train_loss += loss.item() * xb.size(0)

    epoch_train_loss = running_train_loss / len(train_loader.dataset)
    train_losses.append(epoch_train_loss)

    # ---- TEST ----
    model_linear.eval()
    running_test_loss = 0.0

    with torch.no_grad():
        for xb, yb in test_loader:
            xb = xb.to(device)
            yb = yb.to(device)

            outputs = model_linear(xb)
            loss = criterion(outputs, yb)
            running_test_loss += loss.item() * xb.size(0)

    epoch_test_loss = running_test_loss / len(test_loader.dataset)
    test_losses.append(epoch_test_loss)

    print(f"Epoch {epoch+1}: Train Loss = {epoch_train_loss:.4f}, Test Loss = {epoch_test_loss:.4f}")

import matplotlib.pyplot as plt

plt.plot(train_losses, label="Train Loss")
plt.plot(test_losses, label="Test Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Linear Model: Train vs Test Loss")
plt.legend()
plt.show()

with torch.no_grad():
    outputs = model_linear(X_test_t)
    accs = per_class_accuracy(outputs, y_test_t)

for i, acc in enumerate(accs):
    print(f"Class {i} accuracy: {acc:.3f}")

====================
#   Questions 2.e  #
====================

# upload file (works in Jupyter / Colab)
from IPython.display import display
import ipywidgets as widgets

upload = widgets.FileUpload(accept='.txt,.fasta', multiple=False)
display(upload)

# read and clean sequence

def load_sequence_from_upload(upload_widget):
    uploaded_file = list(upload_widget.value.values())[0]
    content = uploaded_file['content'].decode("utf-8")

    # remove ALL whitespace (spaces, newlines, tabs)
    sequence = "".join(content.split())

    return sequence.upper()

sequence = load_sequence_from_upload(upload)

print("Sequence length:", len(sequence))
print("First 50 chars:", sequence[:50])

# generate all possible 9-mers
def generate_kmers(sequence, k=9):
    kmers = []

    for i in range(len(sequence) - k + 1):
        peptide = sequence[i:i+k]
        kmers.append(peptide)

    return kmers

peptides_9mer = generate_kmers(sequence, k=9)

print("Total 9-mers:", len(peptides_9mer))
print("First 5:", peptides_9mer[:5])

# sanity check
valid_aa = set("ACDEFGHIKLMNPQRSTVWY")
invalid = set(sequence) - valid_aa
print("Invalid characters:", invalid)

# upload best non-linear model
from google.colab import files
uploaded = files.upload()

# define the model
model_predict = BetterMLP().to(device)
model_predict.load_state_dict(torch.load("best_model.pth", map_location=device))
model_predict.eval()

# sanity check model dimensions
for name, param in model_predict.named_parameters():
    print(name, param.shape)

# encode peptides to index
# IMPORTANT - to use 'aa_to_idx' from this notebook
import numpy as np

def encode_peptides(peptides, aa_to_idx):
    N = len(peptides)
    X = np.zeros((N, 9, 20), dtype=np.float32)

    for i, peptide in enumerate(peptides):
        for j, aa in enumerate(peptide):
            X[i, j, aa_to_idx[aa]] = 1.0

    return X.reshape(N, -1)

X_spike = encode_peptides(peptides_9mer, aa_to_idx)

# convert to tensor
import torch

X_spike_t = torch.tensor(X_spike, dtype=torch.float32).to(device)

# get logits and probabilites of peptides
model_predict.eval()

with torch.no_grad():
    logits = model_predict(X_spike_t)          # raw outputs
    probs = torch.softmax(logits, dim=1)    # convert to probabilities

# get best allele pre peptide
NEG_CLASS = 6
results = []

for i, peptide in enumerate(peptides_9mer):
    p = probs[i].cpu().numpy()

    pred_class = np.argmax(p)
    pred_score = p[pred_class]

    # ignore NEG predictions
    if pred_class != NEG_CLASS:
        results.append((peptide, pred_class, pred_score))

# top 3 peptides with most confident
results_sorted = sorted(results, key=lambda x: x[2], reverse=True)

top3 = results_sorted[:3]

idx_to_label = {
    0: "A0101",
    1: "A0201",
    2: "A0203",
    3: "A0207",
    4: "A0301",
    5: "A2402",
    6: "NEG"
}

for i, (pep, cls, score) in enumerate(top3):
    print(f"Rank {i+1}:")
    print(f"Peptide: {pep}")
    print(f"Predicted allele: {idx_to_label[cls]}")
    print(f"Confidence: {score:.4f}")
    print()

# histogram of confidence for all peptides (without NEG)
scores = []

for i in range(len(peptides_9mer)):
    p = probs[i].cpu().numpy()

    # ignore NEG class
    p_no_neg = p[:6]

    scores.append(np.max(p_no_neg))

import matplotlib.pyplot as plt

plt.hist(scores, bins=50)
plt.xlabel("Detection Confidence")
plt.ylabel("Number of Peptides")
plt.title("Distribution of Detection Probabilities")
plt.show()

# histogram of confidence for all peptides (with NEG)
scores = []

for i in range(len(peptides_9mer)):
    p = probs[i].cpu().numpy()

    scores.append(np.max(p))

import matplotlib.pyplot as plt

plt.hist(scores, bins=50)
plt.xlabel("Detection Confidence")
plt.ylabel("Number of Peptides")
plt.title("Distribution of Detection Probabilities (With NEG)")
plt.show()

# confidence per class (allele and NEG)
import numpy as np
import matplotlib.pyplot as plt

# probs shape: (num_peptides, 7)
probs_np = probs.cpu().numpy()

# average probability per class
avg_conf_per_class = probs_np.mean(axis=0)

print("Average confidence per class:")
for i, val in enumerate(avg_conf_per_class):
    print(f"Class {i}: {val:.4f}")

plt.bar(range(len(avg_conf_per_class)), avg_conf_per_class)

plt.xlabel("Class")
plt.ylabel("Average Confidence")
plt.title("Average Predicted Probability per Class")

# optional: label with allele names
labels = ["A0101", "A0201", "A0203", "A0207", "A0301", "A2402", "NEG"]
plt.xticks(range(len(labels)), labels, rotation=45)

plt.show()

# count how many peptides per class
import numpy as np

probs_np = probs.cpu().numpy()
preds = np.argmax(probs_np, axis=1)

# counts per class
counts = np.bincount(preds, minlength=7)

print("Counts per class:")
for i, c in enumerate(counts):
    print(f"Class {i}: {c}")

# normalized version - fraction per class
# compare to class acc of the trained model
total = len(preds)
fractions = counts / total

print("\nFraction per class:")
for i, f in enumerate(fractions):
    print(f"Class {i}: {f:.4f}")

# box plot with 95% CI
class_probs = []

for c in range(7):
    class_probs.append(probs_np[:, c])  # all samples, prob of class c
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))

plt.boxplot(class_probs, showfliers=False)

labels = ["A0101", "A0201", "A0203", "A0207", "A0301", "A2402", "NEG"]
plt.xticks(range(1, 8), labels, rotation=45)

plt.ylabel("Predicted Probability")
plt.title("Distribution of Predicted Probabilities per Class")

plt.show()